---
# tasks file for EPICS-base
#---------------------------------------
- name: install requirements
  apt: 
    name:
      - libreadline-gplv2-dev
    update_cache: yes
#---------------------------------------
- name: create EPICS directory
  file:
    path: /opt/epics-R3.15.5/
    state: directory
#---------------------------------------
- name: download EPICS base
  get_url:
    dest: /opt/epics-R3.15.5/base-3.15.5.tar.gz
    url: https://epics.anl.gov/download/base/base-3.15.5.tar.gz
#---------------------------------------
- name: extract files
  unarchive:
    src: /opt/epics-R3.15.5/base-3.15.5.tar.gz
    dest: /opt/epics-R3.15.5/
    remote_src: yes
#---------------------------------------
- name: remove compressed downloaded file
  file:
    path: /opt/epics-R3.15.5/base-3.15.5.tar.gz
    state: absent
#---------------------------------------
- name: check if base dir already exists
  stat:
    path: /opt/epics-R3.15.5/base
  register: base_dir
#---------------------------------------
- name: move directory extracted to base
  command: mv /opt/epics-R3.15.5/base-3.15.5 /opt/epics-R3.15.5/base
  when: base_dir.stat.exists == False
#---------------------------------------
- name: install EPICS base
  make:
    chdir: /opt/epics-R3.15.5/base/
#---------------------------------------
...
